### ISSUE TITLE
Absolute v2 first launch fail issue.

### ISSUE THREAD

**Issue by yjaeseok** [lunchclass/absolute#461]
If I download the absolute v2 source for the first time and run it with the 
```./absolute ```
command, the following error occurs.

```
module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/jakeyoon/Workspace/yjaeseok/absolute/out/server.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

However, if I try to build again, it will run without errors.

Maybe before the server.js file was created, It seems that nodemon is attempting to execute the server.

it seems to need confirmation.

**Comment by yjaeseok** [comment]
Could I try this patch?!

**Comment by yjaeseok** [comment]
issue is closed
